# Generated by Django 5.1.11 on 2025-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('quantity', models.PositiveBigIntegerField()),
                ('fulfillment', models.BooleanField(default=False)),
                ('date_prescribed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
